// Static catalogue constants for the Plan Wizard and related features.
// All values here are client-side; they are joined by productCode / ref at runtime.

import type {
  ClauseLibraryItem,
  FiledProduct,
  FclScheduleEntry,
  PlanTemplate,
  RateCard,
} from '@/lib/types';
import { CoverPattern, SumAssuredBasis, UwMethod, FclPattern, LobType, LivesCovered, EvidencePack, SchemeUsage, ProductArtifactStatus, ProductSalesStatus } from '@/lib/types';



// ── Filed product static catalogue (GTL only, 3 open + 1 closed) ─────────────

export const FILED_PRODUCTS: FiledProduct[] = [
  {
    productCode: 'GTL-STD-001',
    name: 'Group Term Life — Standard',
    description: 'Standard employer-obligatory GTL cover for all employment grades.',
    lob: LobType.GTL,
    subFamily: 'GROUP_TERM',
    coverPattern: [CoverPattern.LEVEL],
    allowedSaBases: [SumAssuredBasis.FLAT, SumAssuredBasis.SALARY_MULTIPLE, SumAssuredBasis.GRADE_SLAB],
    allowedUwMethods: [UwMethod.STP, UwMethod.NSTP, UwMethod.FULL_MEDICAL],
    allowedFclModes: [FclPattern.NONE, FclPattern.OVERALL, FclPattern.BY_GRADE, FclPattern.BY_AGE_BAND],
    allowedUsages: [SchemeUsage.EMPLOYER_EMPLOYEE],
    allowedEmploymentTypes: ['FULL_TIME', 'PART_TIME', 'CONTRACT'],
    allowedLivesCovered: [LivesCovered.MEMBER_ONLY, LivesCovered.MEMBER_SPOUSE],
    defaultEvidencePack: EvidencePack.WITHIN_FCL_MINIMAL,
    allowedEvidencePacks: [EvidencePack.WITHIN_FCL_MINIMAL, EvidencePack.EOI_STANDARD, EvidencePack.EOI_FULL, EvidencePack.EOI_JUMBO],
    filedEnvelope: {
      minEntryAge: 18,
      maxEntryAge: 65,
      ageBasis: 'ALB',
      maxMaturityAge: 70,
      minSumAssured: 100000,
      maxSumAssured: 50000000,
      minGroupSize: 25,
      maxRiskTermYears: 1,
    },
    artifactStatus: ProductArtifactStatus.PUBLISHED,
    salesStatus: ProductSalesStatus.OPEN_TO_NEW_BUSINESS,
    contentHash: 'sha256-gtl-std-001-v3',
    uin: 'IRDAI/GTL/STD/001/2024',
    benefitCodes: ['DEATH_BENEFIT', 'NATURAL_DEATH', 'ACCIDENTAL_DEATH'],
    exclusionCodes: ['SUICIDE_EXCLUSION', 'WAR_EXCLUSION', 'PRE_EXISTING_EXCLUSION'],
    riderCodes: ['ADB_RIDER', 'PTD_RIDER', 'CI_WAIVER_RIDER'],
    reinsurancePosture: 'TREATY',
  },
  {
    productCode: 'GTL-EXEC-002',
    name: 'Group Term Life — Executive',
    description: 'High-sum-assured GTL for senior and executive grades with salary-multiple cover.',
    lob: LobType.GTL,
    subFamily: 'GROUP_TERM',
    coverPattern: [CoverPattern.LEVEL, CoverPattern.REDUCING],
    allowedSaBases: [SumAssuredBasis.SALARY_MULTIPLE, SumAssuredBasis.GRADE_SLAB],
    allowedUwMethods: [UwMethod.NSTP, UwMethod.FULL_MEDICAL, UwMethod.TELE_UW],
    allowedFclModes: [FclPattern.OVERALL, FclPattern.BY_GRADE, FclPattern.BY_AGE_BAND],
    allowedUsages: [SchemeUsage.EMPLOYER_EMPLOYEE],
    allowedEmploymentTypes: ['FULL_TIME'],
    allowedLivesCovered: [LivesCovered.MEMBER_ONLY, LivesCovered.MEMBER_SPOUSE, LivesCovered.FAMILY_VARIANTS],
    defaultEvidencePack: EvidencePack.EOI_STANDARD,
    allowedEvidencePacks: [EvidencePack.EOI_STANDARD, EvidencePack.EOI_FULL, EvidencePack.EOI_JUMBO],
    filedEnvelope: {
      minEntryAge: 21,
      maxEntryAge: 60,
      ageBasis: 'ALB',
      maxMaturityAge: 65,
      minSumAssured: 2000000,
      maxSumAssured: 200000000,
      minGroupSize: 10,
      maxRiskTermYears: 1,
    },
    artifactStatus: ProductArtifactStatus.PUBLISHED,
    salesStatus: ProductSalesStatus.OPEN_TO_NEW_BUSINESS,
    contentHash: 'sha256-gtl-exec-002-v2',
    uin: 'IRDAI/GTL/EXEC/002/2024',
    benefitCodes: ['DEATH_BENEFIT', 'NATURAL_DEATH', 'ACCIDENTAL_DEATH', 'TPD_BENEFIT'],
    exclusionCodes: ['SUICIDE_EXCLUSION', 'WAR_EXCLUSION'],
    riderCodes: ['ADB_RIDER', 'PTD_RIDER', 'CI_WAIVER_RIDER', 'PREMIUM_WAIVER_RIDER'],
    reinsurancePosture: 'TREATY',
  },
  {
    productCode: 'GTL-AFF-003',
    name: 'Group Term Life — Affinity',
    description: 'Non employer–employee affinity cover for associations and member groups.',
    lob: LobType.GTL,
    subFamily: 'GROUP_TERM',
    coverPattern: [CoverPattern.LEVEL],
    allowedSaBases: [SumAssuredBasis.FLAT],
    allowedUwMethods: [UwMethod.STP, UwMethod.NSTP],
    allowedFclModes: [FclPattern.NONE, FclPattern.OVERALL],
    allowedUsages: [SchemeUsage.NON_EMPLOYER_EMPLOYEE],
    allowedEmploymentTypes: ['FULL_TIME', 'PART_TIME', 'CONTRACT', 'SELF_EMPLOYED'],
    allowedLivesCovered: [LivesCovered.MEMBER_ONLY],
    defaultEvidencePack: EvidencePack.WITHIN_FCL_MINIMAL,
    allowedEvidencePacks: [EvidencePack.WITHIN_FCL_MINIMAL, EvidencePack.EOI_STANDARD],
    filedEnvelope: {
      minEntryAge: 18,
      maxEntryAge: 70,
      ageBasis: 'ALB',
      maxMaturityAge: 75,
      minSumAssured: 50000,
      maxSumAssured: 10000000,
      minGroupSize: 50,
      maxRiskTermYears: 1,
    },
    artifactStatus: ProductArtifactStatus.PUBLISHED,
    salesStatus: ProductSalesStatus.OPEN_TO_NEW_BUSINESS,
    contentHash: 'sha256-gtl-aff-003-v1',
    uin: 'IRDAI/GTL/AFF/003/2024',
    benefitCodes: ['DEATH_BENEFIT', 'NATURAL_DEATH', 'ACCIDENTAL_DEATH'],
    exclusionCodes: ['SUICIDE_EXCLUSION', 'WAR_EXCLUSION', 'PRE_EXISTING_EXCLUSION'],
    riderCodes: ['ADB_RIDER'],
    reinsurancePosture: 'NONE_WITHIN_RETENTION',
  },
  {
    // Closed product — present so the wizard can demo a gated / unselectable product.
    productCode: 'GTL-LEGACY-004',
    name: 'Group Term Life — Legacy (Closed)',
    description: 'Legacy GTL product closed to new business. No new plans can be created on this product.',
    lob: LobType.GTL,
    subFamily: 'GROUP_TERM',
    coverPattern: [CoverPattern.LEVEL],
    allowedSaBases: [SumAssuredBasis.FLAT, SumAssuredBasis.SALARY_MULTIPLE],
    allowedUwMethods: [UwMethod.STP, UwMethod.NSTP],
    allowedFclModes: [FclPattern.NONE, FclPattern.OVERALL],
    allowedUsages: [SchemeUsage.EMPLOYER_EMPLOYEE],
    allowedEmploymentTypes: ['FULL_TIME', 'PART_TIME'],
    allowedLivesCovered: [LivesCovered.MEMBER_ONLY],
    defaultEvidencePack: EvidencePack.WITHIN_FCL_MINIMAL,
    allowedEvidencePacks: [EvidencePack.WITHIN_FCL_MINIMAL],
    filedEnvelope: {
      minEntryAge: 18,
      maxEntryAge: 65,
      ageBasis: 'ALB',
      maxMaturityAge: 70,
      minSumAssured: 100000,
      maxSumAssured: 10000000,
      minGroupSize: 25,
      maxRiskTermYears: 1,
    },
    artifactStatus: ProductArtifactStatus.PUBLISHED,
    salesStatus: ProductSalesStatus.CLOSED_TO_NEW_BUSINESS,
    contentHash: 'sha256-gtl-legacy-004-v1',
    uin: 'IRDAI/GTL/LGC/004/2018',
    benefitCodes: ['DEATH_BENEFIT', 'NATURAL_DEATH'],
    exclusionCodes: ['SUICIDE_EXCLUSION', 'WAR_EXCLUSION'],
    riderCodes: [],
    reinsurancePosture: 'TREATY',
  },
];

// ── Clause library ────────────────────────────────────────────────────────────

export const CLAUSE_LIBRARY: ClauseLibraryItem[] = [
  { code: 'DEATH_BENEFIT',          label: 'Death Benefit (All Causes)',       bucket: 'BENEFIT',   mandatory: true,  defaultIncluded: true,  isRider: false },
  { code: 'NATURAL_DEATH',          label: 'Natural Death Cover',              bucket: 'BENEFIT',   mandatory: true,  defaultIncluded: true,  isRider: false },
  { code: 'ACCIDENTAL_DEATH',       label: 'Accidental Death Cover',           bucket: 'BENEFIT',   mandatory: false, defaultIncluded: true,  isRider: false },
  { code: 'TPD_BENEFIT',            label: 'Total & Permanent Disability',     bucket: 'BENEFIT',   mandatory: false, defaultIncluded: false, isRider: false },
  { code: 'SUICIDE_EXCLUSION',      label: 'Suicide / Self-Inflicted Injury',  bucket: 'EXCLUSION', mandatory: true,  defaultIncluded: true,  isRider: false },
  { code: 'WAR_EXCLUSION',          label: 'War & Civil Commotion',            bucket: 'EXCLUSION', mandatory: true,  defaultIncluded: true,  isRider: false },
  { code: 'PRE_EXISTING_EXCLUSION', label: 'Pre-existing Conditions',          bucket: 'EXCLUSION', mandatory: false, defaultIncluded: true,  isRider: false },
  {
    code: 'ADB_RIDER',
    label: 'Accidental Death Benefit',
    bucket: 'RIDER',
    mandatory: false,
    defaultIncluded: false,
    isRider: true,
    trigger: 'Death by accident',
    fundingOptions: ['EMPLOYER_PAID', 'EMPLOYEE_BUY_UP'],
    defaultFunding: 'EMPLOYER_PAID',
    riderSaBasis: SumAssuredBasis.FLAT,
  },
  {
    code: 'PTD_RIDER',
    label: 'Permanent Total Disability',
    bucket: 'RIDER',
    mandatory: false,
    defaultIncluded: false,
    isRider: true,
    trigger: 'PTD as per policy definition',
    fundingOptions: ['EMPLOYER_PAID', 'EMPLOYEE_BUY_UP'],
    defaultFunding: 'EMPLOYER_PAID',
    riderSaBasis: SumAssuredBasis.FLAT,
  },
  {
    code: 'CI_WAIVER_RIDER',
    label: 'Critical Illness Premium Waiver',
    bucket: 'RIDER',
    mandatory: false,
    defaultIncluded: false,
    isRider: true,
    trigger: 'Diagnosis of listed critical illness',
    fundingOptions: ['EMPLOYER_PAID'],
    defaultFunding: 'EMPLOYER_PAID',
    riderSaBasis: SumAssuredBasis.FLAT,
  },
  {
    code: 'PREMIUM_WAIVER_RIDER',
    label: 'Premium Waiver on Disability',
    bucket: 'RIDER',
    mandatory: false,
    defaultIncluded: false,
    isRider: true,
    trigger: 'Total disability of member',
    fundingOptions: ['EMPLOYER_PAID', 'EMPLOYEE_BUY_UP'],
    defaultFunding: 'EMPLOYER_PAID',
    riderSaBasis: SumAssuredBasis.FLAT,
  },
];

// ── Rate cards (product-wired) ────────────────────────────────────────────────

export const PLAN_RATE_CARDS: RateCard[] = [
  {
    ref: 'RC-GTL-STD-001-A',
    productCode: 'GTL-STD-001',
    name: 'Standard GTL — Approved 2024',
    approvalState: 'APPROVED',
    effectiveFrom: '2024-04-01',
    version: 'v3',
    author: 'Actuarial Desk',
    premiumMethodKind: 'PERMILLE_OF_SA',
    dimensions: ['age_band', 'gender'],
    isPreApproved: true,
  },
  {
    ref: 'RC-GTL-STD-001-B',
    productCode: 'GTL-STD-001',
    name: 'Standard GTL — Experience-Rated 2024',
    approvalState: 'APPROVED',
    effectiveFrom: '2024-04-01',
    version: 'v2',
    author: 'Actuarial Desk',
    premiumMethodKind: 'AGE_BANDED',
    dimensions: ['age_band', 'occupation_class'],
    isPreApproved: false,
  },
  {
    ref: 'RC-GTL-STD-001-C',
    productCode: 'GTL-STD-001',
    name: 'Standard GTL — Legacy 2022 (Retired)',
    approvalState: 'RETIRED',
    effectiveFrom: '2022-04-01',
    effectiveTo: '2024-03-31',
    version: 'v1',
    author: 'Actuarial Desk',
    premiumMethodKind: 'PERMILLE_OF_SA',
    dimensions: ['age_band'],
    isPreApproved: false,
  },
  {
    ref: 'RC-GTL-EXEC-002-A',
    productCode: 'GTL-EXEC-002',
    name: 'Executive GTL — Approved 2024',
    approvalState: 'APPROVED',
    effectiveFrom: '2024-04-01',
    version: 'v2',
    author: 'Actuarial Desk',
    premiumMethodKind: 'AGE_BANDED',
    dimensions: ['age_band', 'gender', 'occupation_class'],
    isPreApproved: true,
  },
  {
    ref: 'RC-GTL-AFF-003-A',
    productCode: 'GTL-AFF-003',
    name: 'Affinity GTL — Approved 2024',
    approvalState: 'APPROVED',
    effectiveFrom: '2024-04-01',
    version: 'v1',
    author: 'Actuarial Desk',
    premiumMethodKind: 'PERMILLE_OF_SA',
    dimensions: ['age_band'],
    isPreApproved: true,
  },
];

// ── FCL limit schedule (static, per treaty — mirrors rule engine output) ──────

export const FCL_LIMIT_SCHEDULE: Record<FclPattern, FclScheduleEntry> = {
  [FclPattern.NONE]:        { pattern: FclPattern.NONE,        limits: [] },
  [FclPattern.OVERALL]:     { pattern: FclPattern.OVERALL,     limits: [{ dimension: 'overall',   value: 5000000,  currency: 'INR' }] },
  [FclPattern.BY_GRADE]:    { pattern: FclPattern.BY_GRADE,    limits: [{ dimension: 'grade_A',   value: 10000000, currency: 'INR' }, { dimension: 'grade_B', value: 5000000, currency: 'INR' }] },
  [FclPattern.BY_AGE_BAND]: { pattern: FclPattern.BY_AGE_BAND, limits: [{ dimension: '18-35',     value: 8000000,  currency: 'INR' }, { dimension: '36-55', value: 6000000, currency: 'INR' }, { dimension: '56+', value: 3000000, currency: 'INR' }] },
  [FclPattern.BY_GENDER]:   { pattern: FclPattern.BY_GENDER,   limits: [{ dimension: 'M',         value: 7000000,  currency: 'INR' }, { dimension: 'F', value: 7000000, currency: 'INR' }] },
  [FclPattern.BY_CATEGORY]: { pattern: FclPattern.BY_CATEGORY, limits: [{ dimension: 'SENIOR',    value: 15000000, currency: 'INR' }, { dimension: 'STAFF', value: 5000000, currency: 'INR' }] },
};

// ── Built-in plan templates (6 built-ins per spec) ────────────────────────────

export const BUILTIN_PLAN_TEMPLATES: PlanTemplate[] = [
  { id: 'builtin-flat-10l',     name: 'Flat ₹10 L',           description: 'Uniform ₹10 lakh cover for all grades.',                    tags: ['flat', 'standard'],            isCustom: false, censusAware: false },
  { id: 'builtin-3x-salary',    name: '3× Salary',             description: 'Sum assured = 3× annual salary for every member.',           tags: ['salary-multiple', 'standard'], isCustom: false, censusAware: false },
  { id: 'builtin-5x-exec',      name: '5× Salary Executive',   description: 'Premium salary-multiple cover for senior grades.',           tags: ['salary-multiple', 'executive'], isCustom: false, censusAware: false },
  { id: 'builtin-grade-slab',   name: 'Grade Slab',            description: 'Per-grade SI table seeded from your census grades.',          tags: ['grade-slab', 'census'],        isCustom: false, censusAware: true  },
  { id: 'builtin-family-flat',  name: 'Family Flat ₹5 L',      description: 'Flat ₹5 lakh covering member + spouse.',                    tags: ['flat', 'family'],              isCustom: false, censusAware: false },
  { id: 'builtin-voluntary-tu', name: 'Voluntary Top-up',      description: 'Employee-funded voluntary top-up cover over the base plan.', tags: ['voluntary', 'top-up'],         isCustom: false, censusAware: false },
];

// Returns built-ins merged with any FE-owned custom templates persisted in localStorage.
export function getMergedTemplates(): PlanTemplate[] {
  const raw = typeof window !== 'undefined' ? localStorage.getItem('gtl.plan-templates.v1') : null;
  const customs: PlanTemplate[] = raw ? (JSON.parse(raw) as PlanTemplate[]) : [];
  return [...BUILTIN_PLAN_TEMPLATES, ...customs];
}

// Re-export all constants from the original constants/index barrel
export * from './constants/index';
