export const inputMocks = {
  types: ["text", "email", "password", "number", "date"] as const,

  placeholders: {
    default: "Default input",
    disabled: "Disabled input",
    error: "Error state",
    clientName: "Enter client name...",
    autoGenerated: "Auto-generated",
    policyNumber: "Enter policy number",
    amount: "Enter amount",
    password: "Enter password",
  },

  values: {
    preFilled: "With pre-filled value",
    quotation: "Q-2024-001",
  },
};
