import type { Meta, StoryObj } from "@storybook/react";
import { Input } from "@/components/ui/input";
import { inputMocks } from "@/stories/__mocks__";

const meta: Meta<typeof Input> = {
  title: "UI/Input",
  component: Input,
  tags: ["autodocs"],
  argTypes: {
    type: {
      control: "select",
      options: inputMocks.types,
    },
    disabled: { control: "boolean" },
  },
};

export default meta;
type Story = StoryObj<typeof Input>;

export const AllVariants: Story = {
  render: () => (
    <div className="flex flex-col gap-3 max-w-sm">
      <Input type="text" placeholder={inputMocks.placeholders.default} />
      <Input type="text" defaultValue={inputMocks.values.preFilled} />
      <Input
        type="text"
        placeholder={inputMocks.placeholders.disabled}
        disabled
      />
      <Input
        type="text"
        placeholder={inputMocks.placeholders.error}
        aria-invalid={true}
      />
    </div>
  ),
};

// --- States ---

export const Default: Story = {
  args: { type: "text" },
};

export const WithPlaceholder: Story = {
  args: { type: "text", placeholder: inputMocks.placeholders.clientName },
};

export const WithValue: Story = {
  args: { type: "text", defaultValue: inputMocks.values.quotation },
};

export const Disabled: Story = {
  args: {
    type: "text",
    placeholder: inputMocks.placeholders.autoGenerated,
    disabled: true,
  },
};

export const ErrorState: Story = {
  args: {
    type: "text",
    placeholder: inputMocks.placeholders.policyNumber,
    "aria-invalid": true,
  },
};

// --- Input Types ---

export const DateInput: Story = {
  args: { type: "date" },
};

export const NumberInput: Story = {
  args: { type: "number", placeholder: inputMocks.placeholders.amount },
};

export const PasswordInput: Story = {
  args: { type: "password", placeholder: inputMocks.placeholders.password },
};
