import fs from 'fs/promises';
import path from 'path';

const repoRoot = process.cwd();
const appDir = path.join(repoRoot, 'src', 'app');
const routesDir = path.join(repoRoot, 'src', 'routes');
const outputPath = path.join(repoRoot, 'docs', 'planning', 'ROUTE-INVENTORY.md');

async function walk(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        return walk(fullPath);
      }
      return [fullPath];
    }),
  );

  return files.flat();
}

function appFileToRoutePath(filePath) {
  const relative = path.relative(appDir, filePath);
  const normalized = relative.replace(/\\/g, '/');
  const withoutPage = normalized.replace(/(?:^|\/)page\.tsx?$/, '');

  if (!withoutPage) {
    return '/';
  }

  const segments = withoutPage
    .split('/')
    .filter(Boolean)
    .map((segment) => {
      const optionalCatchAll = segment.match(/^\[\[\.\.\.(.+)\]\]$/);
      if (optionalCatchAll) return `:${optionalCatchAll[1]}*`;

      const catchAll = segment.match(/^\[\.\.\.(.+)\]$/);
      if (catchAll) return `:${catchAll[1]}*`;

      const dynamic = segment.match(/^\[(.+)\]$/);
      if (dynamic) return `:${dynamic[1]}`;

      return segment;
    });

  return `/${segments.join('/')}`;
}

function normalizeImportPath(importerPath, importTarget) {
  const resolved = path.resolve(path.dirname(importerPath), importTarget);
  return path.relative(repoRoot, resolved).replace(/\\/g, '/');
}

async function readManifestText() {
  try {
    const routeFiles = await walk(routesDir);
    const manifestFiles = routeFiles.filter((file) => /manifest\.(t|j)sx?$/.test(path.basename(file)));

    if (manifestFiles.length === 0) {
      return '';
    }

    const contents = await Promise.all(manifestFiles.map((file) => fs.readFile(file, 'utf8')));
    return contents.join('\n');
  } catch (error) {
    return '';
  }
}

function routePathToNextStyle(routePath) {
  if (routePath === '/') return '/';

  const segments = routePath
    .split('/')
    .filter(Boolean)
    .map((segment) => {
      const catchAll = segment.match(/^:(.+)\*$/);
      if (catchAll) return `[...${catchAll[1]}]`;

      const dynamic = segment.match(/^:(.+)$/);
      if (dynamic) return `[${dynamic[1]}]`;

      return segment;
    });

  return `/${segments.join('/')}`;
}

function hasManifestEntry(routePath, manifestText) {
  if (!manifestText) return false;

  const candidates = new Set([routePath, routePathToNextStyle(routePath)]);

  return [...candidates].some((candidate) => {
    const escaped = candidate.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const pattern = new RegExp(`path\\s*[:=]\\s*['\"]${escaped}['\"]|['\"]path['\"]\\s*:\\s*['\"]${escaped}['\"]`);
    return pattern.test(manifestText);
  });
}

async function collectInventory() {
  let files;
  try {
    files = await walk(appDir);
  } catch (err) {
    console.error(`Error: could not walk ${appDir}. Is this a Next.js project?`);
    process.exitCode = 1;
    return [];
  }
  const routeFiles = files.filter((file) => /page\.tsx?$/.test(file));
  const manifestText = await readManifestText();
  const importPattern = /import\s+[\s\S]*?from\s+['\"]([^'\"]+\.json)['\"];?/g;

  const rows = [];

  for (const file of routeFiles) {
    const content = await fs.readFile(file, 'utf8');
    const matches = [...content.matchAll(importPattern)];

    for (const match of matches) {
      const routePath = appFileToRoutePath(file);
      const schemaFile = normalizeImportPath(file, match[1]);
      rows.push({
        routePath,
        schemaFile,
        manifestEntryExists: hasManifestEntry(routePath, manifestText),
        migrationStatus: 'legacy',
        routeFile: path.relative(repoRoot, file).replace(/\\/g, '/'),
      });
    }
  }

  rows.sort((a, b) => a.routePath.localeCompare(b.routePath) || a.schemaFile.localeCompare(b.schemaFile));
  return rows;
}

function renderMarkdown(rows) {
  const generatedAt = new Date().toISOString().slice(0, 10);
  const rowLines = rows.map((row) => {
    const manifestValue = row.manifestEntryExists ? 'yes' : 'no';
    return `| \`${row.routePath}\` | \`${row.schemaFile}\` | ${manifestValue} | ${row.migrationStatus} | \`${row.routeFile}\` |`;
  });

  return `# Route Inventory

**Status:** Generated inventory
**Date:** ${generatedAt}

This file is generated by \`npm run inventory:routes\` using \`scripts/inventory_routes.mjs\`.

It lists every route file in \`src/app/**/page.tsx\` that directly imports a schema JSON file.

Interpretation:

- \`migration status = legacy\` means the route still directly imports a schema JSON file
- \`route manifest entry exists\` is based on current files under \`src/routes/\`; if no manifest files exist yet, this remains \`no\`

| Route path | Schema file | Route manifest entry exists | Migration status | Route file |
|---|---|---|---|---|
${rowLines.join('\n')}
`;
}

async function main() {
  const rows = await collectInventory();
  const markdown = renderMarkdown(rows);
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, markdown);
  console.log(`Wrote route inventory to ${path.relative(repoRoot, outputPath)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
