# Dev environment overrides
replicaCount: 1

ingress:
  host: keystone-ui-dev.anairacloud.com
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
    external-dns.alpha.kubernetes.io/hostname: keystone-ui-dev.anairacloud.com

env:
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1536Mi

# No database — IRSA / Secrets Manager not required.
serviceAccount:
  irsaRoleArn: ""

externalSecret:
  enabled: false
  secretArn: ""
